run-all: run-root run-app1 run-app2

run-root:
	@echo ===================== Root =====================
	go run main.go
	@echo

run-app1:
	@echo ===================== App1 =====================
	go run cmd/app1/main.go a b c
	@echo

run-app2:
	@echo ===================== App2 =====================
	go run cmd/app2/main.go 1 2
	@echo
